from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.index),
    path('login/', views.login),
    path('register/', views.reg),
    path('verify_otp/', views.verify_otp),
    path('resend_otp/', views.resend_otp, name='resend_otp'),
    path('forgot_password/', views.forgot_password),
    path('verify_reset_otp/', views.verify_reset_otp),
    path('resend_reset_otp/', views.resend_reset_otp, name='resend_reset_otp'),
    path('new_password/', views.new_password),
    path('creators/', views.creators),
    path('artists/', views.artists),
    path('admin_users/', views.manageusers),
    path('blockuser/<id>/', views.blockuser),
    path('unblockuser/<id>/', views.unblockuser),
    path('project/', views.project),
    path('manageprojects/', views.manageprojects),
    path('delete_project/<int:id>/', views.admin_delete_project),
    path('blockproject/<id>/', views.blockproject),
    path('unblockproject/<id>/', views.unblockproject),
    path('admindashboard/', views.admindashboard), 
    path('manage_admin/manage_casting/', views.manage_castingcalls),
    path('manage_admin/delete_casting/<int:id>/', views.admin_delete_casting),
    path('manage_admin/manage_posts/', views.manage_artistposts),
    path('manage_admin/delete_post/<int:id>/', views.admin_delete_post),
    path('manage_admin/manage_comments/', views.manage_allcomments),
    path('manage_admin/delete_comment/<int:id>/<str:type>/', views.admin_delete_comment),
    path('casting/', views.post_casting_call),
    path('my_projects/', views.my_projects),
    path('my_castingcalls/', views.my_castingcalls),
    path('artprofile/', views.artprofile),
    path('editavatar/', views.editavatar),
    path('editcoverphoto/', views.editcover),
    path('castingcalls/', views.castingcalls),
    path('applications/', views.applications),
    path('manageapplication/', views.manageapplication),
    path('myapplications/', views.myapplications),
    path('findprojects/', views.findprojects),
    path('projectlike/', views.project_like),
    path('projectcomment/', views.project_comment),
    path('view_my_posts/', views.view_my_posts),
    path('artistlike/', views.artist_like),
    path('artistcomment/', views.artist_comment),
    path('logout/', views.logout),
    path('findartists/', views.findartists, name='findartists'),
    path('like_artist_post/', views.creator_artist_like),
    path('comment_artist_post/', views.creator_artist_comment),
    path('edit_artist_comment/<int:comment_id>/', views.edit_artist_comment),
    path('delete_artist_comment/<int:comment_id>/', views.delete_artist_comment),
    path('creator_profile/', views.creator_profile),
    path('project_creator_comment/', views.project_creator_comment),
    path('edit_project_comment/<int:comment_id>/', views.edit_project_comment, name='edit_project_comment'),
    path('delete_project_comment/<int:comment_id>/', views.delete_project_comment, name='delete_project_comment'),
    path('view_artist_profile/<int:id>/', views.view_artist_profile, name='view_artist_profile'),

    # Chat URLs
    path('chat/', views.chat_home, name='chat_home'),
    path('api/search-users/', views.search_users, name='search_users'),
    path('api/get-thread/<int:user_id>/', views.get_chat_thread, name='get_chat_thread'),
    path('artists/delete_post/<int:post_id>/', views.delete_artist_post, name='delete_artist_post'),
    path('artists/edit_post/<int:post_id>/', views.edit_artist_post, name='edit_artist_post'),
    path('api/get-user-threads/', views.get_user_threads, name='get_user_threads'),
    path('api/get-unread-count/', views.get_global_unread_count, name='get_global_unread_count'),
    path('api/send-message/', views.send_message, name='send_message'),
    path('api/get-messages/<int:thread_id>/', views.get_messages, name='get_messages'),
    path('api/delete-message/', views.delete_message, name='delete_message'),
    path('api/edit-message/', views.edit_message, name='edit_message'),
    path('api/update-typing-status/', views.update_typing_status, name='update_typing_status'),
    path('api/clear-chat/', views.clear_chat, name='clear_chat'),
    path('creators/casting/<int:id>/', views.edit_casting_call),
    path('delete_casting/<int:id>/', views.delete_casting_call),
    path('view_creator_profile/<int:id>/', views.view_creator_profile, name='view_creator_profile'),
    path('creators/projects/<int:id>/', views.edit_project),
    path('creators/delete_project/<int:id>/', views.delete_project),
    path('settings/', views.settings_page, name='settings'),
    path('deactivate_account/', views.deactivate_account, name='deactivate_account'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('user_contact/', views.user_contact, name='user_contact'),
    path('change_password/', views.change_password, name='change_password'),
    path('verify_profile_otp/', views.verify_profile_otp, name='verify_profile_otp'),
    path('resend_profile_otp/', views.resend_profile_otp, name='resend_profile_otp'),
    path('verify_delete_otp/', views.verify_delete_otp, name='verify_delete_otp'),
    path('resend_delete_otp/', views.resend_delete_otp, name='resend_delete_otp'),
    path('confirm_delete/', views.confirm_delete, name='confirm_delete'),
    path('cancel_signup/', views.cancel_signup, name='cancel_signup'),
]