# Generated by Django 5.2.8 on 2025-11-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('artist', 'Artist')], max_length=20)),
                ('creator_role', models.CharField(blank=True, choices=[('director', 'Director'), ('producer', 'Producer')], max_length=20, null=True)),
                ('artist_role', models.CharField(blank=True, choices=[('actor', 'Actor'), ('editor', 'Editor'), ('photographer', 'Photographer')], max_length=20, null=True)),
                ('password', models.CharField(max_length=100)),
                ('rights', models.CharField(default='user', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
