# Generated by Django 5.2.8 on 2025-11-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='artist_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='creator_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=50)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('project_status', models.CharField(max_length=50)),
                ('rights', models.CharField(default='project', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
