# Generated by Django 5.2.8 on 2025-11-11 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_artist_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=255)),
                ('role_category', models.CharField(max_length=50)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('required_gender', models.CharField(default='Any', max_length=20)),
                ('age_range', models.CharField(blank=True, max_length=50, null=True)),
                ('compensation', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
                ('project_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
    ]
