# Generated by Django 5.2.8 on 2025-11-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_artistdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistdetails',
            name='required_gender',
        ),
        migrations.AddField(
            model_name='artistdetails',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
