# Generated by Django 5.2.8 on 2025-11-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_artistdetails_required_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdetails',
            name='about',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='artistdetails',
            name='location',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='artistdetails',
            name='skillsInput',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='artistdetails',
            name='title',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
