# Generated by Django 5.2.8 on 2025-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_artistdetails_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdetails',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistdetails',
            name='instagram',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artistdetails',
            name='personalwebsite',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artistdetails',
            name='phone',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artistdetails',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artistdetails',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='artistdetails',
            name='skillsInput',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artistdetails',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
