# Generated by Django 5.2.8 on 2025-11-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_artistdetails_email_artistdetails_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistdetails',
            old_name='skillsInput',
            new_name='skillsinput',
        ),
        migrations.RemoveField(
            model_name='artistdetails',
            name='email',
        ),
    ]
