# Generated by Django 5.2.8 on 2025-11-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_skillsinput_artistdetails_skillsinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdetails',
            name='gender',
            field=models.CharField(default='Not interested to say', max_length=100),
        ),
    ]
