# Generated by Django 5.2.8 on 2025-11-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_artistdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingcall',
            name='role_requirements',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
