# Generated by Django 5.2.8 on 2025-11-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_castingcall_role_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdetails',
            name='avatarphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='artistdetails',
            name='coverphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
