# Generated by Django 5.2.8 on 2025-11-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_artistdetails_avatarphoto_artistdetails_coverphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistdetails',
            name='avatarphoto',
        ),
        migrations.RemoveField(
            model_name='artistdetails',
            name='coverphoto',
        ),
    ]
