# Generated by Django 5.2.8 on 2025-11-21 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_artistdetails_avatarphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_role', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
                ('casting_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.castingcall')),
            ],
        ),
    ]
