# Generated by Django 5.2.8 on 2025-11-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_applications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='casting_title',
            new_name='casting_details',
        ),
    ]
