# Generated by Django 5.2.8 on 2025-11-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_casting_title_applications_casting_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='applied_role',
        ),
    ]
