# Generated by Django 5.2.8 on 2025-11-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_applications_applied_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='casting_details',
            new_name='casting_id',
        ),
    ]
