# Generated by Django 5.2.8 on 2025-11-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_casting_details_applications_casting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='details_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.artistdetails'),
        ),
    ]
