# Generated by Django 5.2.8 on 2025-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_applications_details_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
