# Generated by Django 5.2.8 on 2025-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_applications_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='application_status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
