# Generated by Django 5.2.8 on 2025-11-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_photopost_post_videopost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='photopost',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='caption',
        ),
        migrations.AddField(
            model_name='photopost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
        ),
    ]
