# Generated by Django 5.2.8 on 2025-11-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_artistcomment_artistlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdetails',
            name='avatarphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
