# Generated by Django 5.2.8 on 2025-11-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_artistdetails_avatarphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdetails',
            name='coverphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
