# Generated by Django 5.2.8 on 2025-12-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_artistdetails_coverphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.projectcomment'),
        ),
    ]
