# Generated by Django 5.2.7 on 2026-02-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.artistcomment'),
        ),
    ]
