# Generated by Django 5.2.7 on 2026-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_artistcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videopost',
            name='start_time',
            field=models.FloatField(default=0.0),
        ),
    ]
