# Generated by Django 5.2.7 on 2026-02-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_videopost_end_time_videopost_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
