# Generated by Django 5.2.7 on 2026-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_project_image_project_video_project_video_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='performance_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/photos/'),
        ),
        migrations.AddField(
            model_name='applications',
            name='performance_video',
            field=models.FileField(blank=True, null=True, upload_to='applications/videos/'),
        ),
    ]
