# Generated by Django 5.2.7 on 2026-02-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_applications_performance_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='performance_photo',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='performance_video',
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applications/attachments/')),
                ('file_type', models.CharField(default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='myapp.applications')),
            ],
        ),
    ]
