# Generated by Django 5.2.7 on 2026-03-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_chatmessage_deleted_by_sender_chatmessage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
